version: "3.2"
services:

  #PHP Service
  aston-app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    container_name: aston-app
    ports:
      - "89:8080"
    volumes:
      - ./:/var/www/aston


  aston-db:
    image: postgres:9.5-alpine
    restart: unless-stopped
    container_name: aston-db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=aston
    ports:
      - "5433:5432"




